
version: 2

models:
    - name: onadata_from_airbyte
      description: "A packaged modelt to create a dedicated table from the JSON inside an Ona Data submission ingested via Airbyte"
      columns:
          - name: _id
            description: "The primary key for this table, the submission id"
            tests:
                - unique
                - not_null
